# 'sonar-project.properties' file is mandatory because it serves as the central configuration source for the SonarQube scanner.
# The sonar-project.properties file is a configuration file that tells the SonarQube Scanner what project to analyze and how to analyze it.
sonar.projectKey=devboard 
# This is the unique ID used by the SonarQube Server to identify your project. It must be unique across your entire instance.
sonar.projectName=devboard
# This is the display name of the project as it appears on the dashboard in the SonarQube Web UI.
sonar.sources=backend,frontend
# : This tells the scanner where your code lives. Instead of scanning the entire repository, it will focus specifically on the backend and frontend folders.