# Goal: to deploy the built images from CI steps once the CI workflow is successful. 
# This workflow will be triggered by the CI workflow once it is successful.

name: CD-practice

on: 
    workflow_run:
        workflows: ["CI"]
        types:
            - completed
        branches: [advanced]

jobs: 
    deploy:
        runs-on: self-hosted
        steps: 
            - name: Checkout Code
              uses: actions/checkout@v7

            - name: Copy example env file to .env           # Copies the .env.example file to .env , it contains the necessary environment variables required for the backend to run.
              run: cp .env.example .env  

            - name: Docker Setup [Login]
              uses: docker/login-action@v4
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Deploy containers using docker-compose
              run: |                                        # The pipe symbol (|) is YAML syntax that allows you to write multiple lines of commands instead of just one.
                docker-compose pull                         
                docker-compose up -d 
              
              # Pulls the latest images from Docker Hub to the server, for the services defined in the docker-compose.yml file.
              # 'up tells docker compose to start the containers, and '-d' runs them in detached mode (in the background).
              # This step tells the automation server to download the newest versions of your application's Docker images and then start (or restart) those containers in the background so your app goes live.