# Goal : Build the image for Devboard frontend and push to Docker Hub
# Requires docker hub username and password/PAT

name: CI

on:
  push:
    branches: [master]

jobs:
  builld-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v7

      # 2. Log in to Docker Hub
      - name: Login to docker hub
        uses: docker/login-action@v4
        with: 
          username:  ${{ vars.DOCKERHUB_USERNAME }}
          password:  ${{ secrets.DOCKERHUB_TOKEN }}
          
      # 3: Build and push the Docker image to your repository
      - name: Docker build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/devboard-fe-master:latest
        
      

    
  
    
