# Goal:  Lint, Build, Test the code for Frontend & Backend and push the images to DockerHub.
 
name: CI

on: 
    push:
        branches: [advanced]

jobs: 
    front-end:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code                                   # Both frontend and backend code will be checked out in this step
              uses: actions/checkout@v7

            - name: Setup NodeJs                                    # This borrows a pre-made tool created by GitHub designed to install Node.js.
              uses: actions/setup-node@v6
              with:
                node-version: '20'                                  # Version of Node.js to install
                cache: npm                                          # This activates a "memory" feature. Instead of downloading all your project's code packages from the internet every single time, GitHub saves a copy of them. This makes your future builds run much faster.
                cache-dependency-path: frontend/package-lock.json   # This tells GitHub exactly where to look to see what packages your project needs. GitHub looks at this specific file (package-lock.json) inside your frontend folder.
        
            - name: Install npm Packages
              run: npm ci
            #   working-directory: frontend

            - name: Frontend Linter
              run: npm run lint
            #   working-directory: frontend
        
            # - name: Build
            #   run: npm run build
            #   working-directory: frontend

            - name: Run tests
              run: npm run test
            #   working-directory: frontend

    # backend:     

