# Goal - to run the end to end DevSecOps CI Pipeline
name: DevSecOps Practice
on:
    push:
        branches: [master]

jobs:
    # The different workflows will run in parallel, and each workflow will have its own set of jobs. 
    # The jobs within a workflow will also run in parallel, unless you specify dependencies between them.
    code-quality:
        uses: ./.github/workflows/code-quality.yml

    secret-scanning:
        uses: ./.github/workflows/secret-scanning.yml

    dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml
