# Goal - To ensure no secrets have been leaked in the code

name: Secret Scanning

on:
    workflow_call:                                                  # used to indicate that a workflow can be called by another workflow.

jobs:
    scan-secrets:
        runs-on: ubuntu-latest
        steps:
            - name: Code checkout
              uses: actions/checkout@v7
              with:
                fetch-depth: 0                                      
                                                                    # No. of commits to fetch. 
                                                                    # By default, GitHub Actions fetches only the latest commit. 
                                                                    # Setting this to 0 fetches all commits, which is necessary for a comprehensive secret scan.
                                                                    # This ensures that the entire history of the repository (all the commits) is fetched, which is necessary for a comprehensive secret scan.

            - name: Git Leaks Scanning
              uses: gitleaks/gitleaks-action@v3
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          # This is a special token provided by GitHub Actions that allows the workflow to interact with the GitHub API. It is used here to authenticate the GITLEAKS action and allow it to access the repository's data for scanning.
            
                # IMPORTANT: Hence, it is recommended not to include the secrets in workflow & run the workflow on a pull request as users may have access to secrets in the repository and can use this workflow to exfiltrate them.
            


